/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelha2;

/**
 *
 * @author Wilian.M
 */
public class Jogo extends javax.swing.JFrame {
public boolean jog1=true;
public boolean jog2=true;
public int contpos=0;
public int k=0,i=0;
int op;
public String lin1,lin2,lin3,colun1,colun2,colun3,diago1,diago2;
String[][]matriz=new String[3][3];

    
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botaoreiniciar = new javax.swing.JButton();
        txtvisor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao4.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao5.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao6.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botao7.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao8.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao9.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botaoreiniciar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoreiniciar.setText("REINICIAR");
        botaoreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoreiniciarActionPerformed(evt);
            }
        });

        txtvisor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtvisor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtvisor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(botaoreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botao9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvisor)
                .addGap(18, 18, 18)
                .addComponent(botaoreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void VerificaJogadorDaVez(){
    if(jog1&&jog2){
        this.op=1;
        jog1=false;
        jog2=true;
        txtvisor.setText("vez do jogador O");
    }else if(jog1&&jog2==false){
        this.op=1;
        jog1=false;
        jog2=true;
        txtvisor.setText("vez do jogador O"); 
        
    }else{
        this.op=2;
        jog1=true;
        jog2=false;
        txtvisor.setText("vez do jogador X");
    }
}
public void LimpaPosicoes(){
    for(i=0;i<3;i++){
        for(k=0;k<3;k++){
            matriz[i][k]="";
            System.out.println(matriz[i][k]);
        }
    }
}
public void DesativaBotoes(){
    botao1.setEnabled(false);
    botao2.setEnabled(false);
    botao3.setEnabled(false);
    botao4.setEnabled(false);
    botao5.setEnabled(false);
    botao6.setEnabled(false);
    botao7.setEnabled(false);
    botao8.setEnabled(false);
    botao9.setEnabled(false);
}
public void VerificaPosicoes(){
    contpos=0;
    for(i=0;i<3;i++){
        for(k=0;k<3;k++){
            if(matriz[i][k]=="x"|matriz[i][k]=="o"){
                contpos+=1;
                
            }
        }
    }
}
public void VerificaVencedor(){
    //linhas
    lin1=matriz[0][0]+matriz[0][1]+matriz[0][2];
    lin2=matriz[1][0]+matriz[1][1]+matriz[1][2];
    lin3=matriz[2][0]+matriz[2][1]+matriz[2][2];
    //colunas
    colun1=matriz[0][0]+matriz[1][0]+matriz[2][0];
    colun2=matriz[0][1]+matriz[1][1]+matriz[2][1];
    colun3=matriz[0][2]+matriz[1][2]+matriz[2][2];
    //diagonais
    diago1=matriz[0][0]+matriz[1][1]+matriz[2][2];
    diago2=matriz[0][2]+matriz[1][1]+matriz[2][0];
    
    if(lin1.equals("xxx")|lin2.equals("xxx")|lin3.equals("xxx")|colun1.equals("xxx")|colun2.equals("xxx")|colun3.equals("xxx")|diago1.equals("xxx")|diago2.equals("xxx")){
        txtvisor.setText("o vencedor é o X");
        DesativaBotoes();
        
    }else if(lin1.equals("ooo")|lin2.equals("ooo")|lin3.equals("ooo")|colun1.equals("ooo")|colun2.equals("ooo")|colun3.equals("ooo")|diago1.equals("ooo")|diago2.equals("ooo")){
        txtvisor.setText("o vencedor é o O");
        DesativaBotoes();
    }else if(contpos==9){
        txtvisor.setText("Deu Velha");
    }
}
    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // botão 1
        VerificaJogadorDaVez();
        if(op==1){
        botao1.setText("X");
        matriz[0][0]="x";
        }else{
        botao1.setText("O");
        matriz[0][0]="o";   
        }
        botao1.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        // botão 2
        VerificaJogadorDaVez();
        if(op==1){
        botao2.setText("X");
        matriz[0][1]="x";
        }else{
        botao2.setText("O");
        matriz[0][1]="o";   
        }
        botao2.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        // botão 3
        VerificaJogadorDaVez();
        if(op==1){
        botao3.setText("X");
        matriz[0][2]="x";
        }else{
        botao3.setText("O");
        matriz[0][2]="o";   
        }
        botao3.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        // botão 4
        VerificaJogadorDaVez();
        if(op==1){
        botao4.setText("X");
        matriz[1][0]="x";
        }else{
        botao4.setText("O");
        matriz[1][0]="o";   
        }
        botao4.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        // botão 5
        VerificaJogadorDaVez();
        if(op==1){
        botao5.setText("X");
        matriz[1][1]="x";
        }else{
        botao5.setText("O");
        matriz[1][1]="o";   
        }
        botao5.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
       // botão 6
        VerificaJogadorDaVez();
        if(op==1){
        botao6.setText("X");
        matriz[1][2]="x";
        }else{
        botao6.setText("O");
        matriz[1][2]="o";   
        }
        botao6.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
          // botão 7
        VerificaJogadorDaVez();
        if(op==1){
        botao7.setText("X");
        matriz[2][0]="x";
        }else{
        botao7.setText("O");
        matriz[2][0]="o";   
        }
        botao7.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        // botão 8
        VerificaJogadorDaVez();
        if(op==1){
        botao8.setText("X");
        matriz[2][1]="x";
        }else{
        botao8.setText("O");
        matriz[2][1]="o";   
        }
        botao8.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        // botão 9
        VerificaJogadorDaVez();
        if(op==1){
        botao9.setText("X");
        matriz[2][2]="x";
        }else{
        botao9.setText("O");
        matriz[2][2]="o";   
        }
        botao9.setEnabled(false);
        VerificaPosicoes();
        VerificaVencedor();
    }//GEN-LAST:event_botao9ActionPerformed

    private void botaoreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoreiniciarActionPerformed
        // reiniciar
        botao1.setText("");
        botao1.setEnabled(true);
        botao2.setText("");
        botao2.setEnabled(true);
        botao3.setText("");
        botao3.setEnabled(true);
        botao4.setText("");
        botao4.setEnabled(true);
        botao5.setText("");
        botao5.setEnabled(true);
        botao6.setText("");
        botao6.setEnabled(true);
        botao7.setText("");
        botao7.setEnabled(true);
        botao8.setText("");
        botao8.setEnabled(true);
        botao9.setText("");
        botao9.setEnabled(true);
        LimpaPosicoes();
        txtvisor.setText("");
        jog1=true;
        jog2=true;
    }//GEN-LAST:event_botaoreiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoreiniciar;
    private javax.swing.JTextField txtvisor;
    // End of variables declaration//GEN-END:variables
}
